### ISSUE TITLE
Ponto de melhoria

### ISSUE THREAD

**Issue by jordyalcides** [gleicekelly13/3-column-preview-card-component#1]
Olá Gleice!

Dando uma olhada neste repositório notei que faltou um README para ficar completo.
Um README bem construído sempre dá um boost legal para que os recrutadores possam se interessar de cara pelo projeto!

_Caso queira mais instruções sobre como fazer um README legal, eu já fiz um vídeo sobre o assunto, confere lá:_
[Como fazer um README para o seu projeto](https://app.nutror.com/v3/curso/6bdfb50e6f2579177147aad1ac55aa085eb54342/comunidade-code/aula/5202928)

**Comment by gleicekelly13** [comment]
Oi Jordy!
Mais uma vez, obrigada pelo feedback, tbm gostei muito do vídeo sobre Readme. Agora já está inserido no projeto.
Muito obrigada!
